added jfrog
Signed-off-by: kshitiz-okahu <152476347+kshitiz-okahu@users.noreply.github.com>

diff --git a/.github/workflows/publish-to-jfrog.yml b/.github/workflows/publish-to-jfrog.yml
--- a/.github/workflows/publish-to-jfrog.yml
+++ b/.github/workflows/publish-to-jfrog.yml
@@ -38,17 +38,17 @@ jobs:
         with:
           ref: ${{ inputs.branch }}
 
-      - name: 🔎 Validate version format
-      # valid versions are. 0.5.0, 0.5.0a1, 0.5.0b1
-        run: |
-          version="${{ inputs.version }}"
-          if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+((a|b)[0-9]*)?$ ]]; then
-            echo "::error::Invalid version format"
-            echo "❌ Expected: x.y.z, x.y.za, x.y.zaN, x.y.zb, or x.y.zbN"
-            echo "❌ Provided: $version"
-            exit 1
-          fi
-          echo "✅ Version format is valid: $version"
+      # - name: 🔎 Validate version format
+      # # valid versions are. 0.5.0, 0.5.0a1, 0.5.0b1
+      #   run: |
+      #     version="${{ inputs.version }}"
+      #     if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+((a|b)[0-9]*)?$ ]]; then
+      #       echo "::error::Invalid version format"
+      #       echo "❌ Expected: x.y.z, x.y.za, x.y.zaN, x.y.zb, or x.y.zbN"
+      #       echo "❌ Provided: $version"
+      #       exit 1
+      #     fi
+      #     echo "✅ Version format is valid: $version"
 
       - name: 📝 Update version in pyproject.toml
         run: |
